language: python
python:
  - "3.6"

env:
  global:
    - DATABASE_URL=postgres://postgres:@localhost:5432/epicmail_db

services:
  - postgresql

before_script:
  - "psql -c 'create database epicmail_db;' -U postgres"

install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - pytest --cov
  - coverage

after_success:
  - coveralls
